### ISSUE TITLE
Easier way to ensure video plays inline on iPhone

### ISSUE THREAD

**Issue by jaywardell** [gilesvangruisen/Swift-YouTube-Player#100]
YTPlayer wants to play videos fullscreen on iPhone and inline on iPad.  There is a setting to change this in the playerVars so that the video always plays inline, but it took some time and research to get it working for me.

I propose a new property to make this easier for new users:

    /// by default, the youtube player will not play inline on iPhone
    /// setting this to true will force it to play inline
    var alwaysPlayInline : Bool {
        get {
            if let playsinline = playerVars["playsinline"] as? String {
                return playsinline == "1"
            }
            return false
        }
        set {
            playerVars["playsinline"] = "\(newValue ? 1 : 0)" as AnyObject?
          }
    }

**Comment by gilesvangruisen** [comment]
Nice, I like this change. Mind submitting a PR for this, too?

**Comment by gregattra** [comment]
@jaywardell could you explain how you managed to successfully prevent the video from entering fullscreen on play?

**Comment by JacopoKenzo** [comment]
Using the same technique I would add the other parameters like: `rel`, `showInfo`, `controls` etc
For an easy setup of the player!

**Comment by davidseek** [comment]
added this, but it still plays in fullscreen... any idea?

**Comment by Vitalie-Andries** [comment]
jaywardell 
Try to add this code... but nothing... many errors... maybe I not use correctly it. Can you help me please?
on iPad it's ok but on iPhone still goes in fullscreen... wont play inLine... I use WKWebView
Thanks in advance.

**Comment by Vitalie-Andries** [comment]
> YTPlayer wants to play videos fullscreen on iPhone and inline on iPad. There is a setting to change this in the playerVars so that the video always plays inline, but it took some time and research to get it working for me.
> 
> I propose a new property to make this easier for new users:
> 
> ```
> /// by default, the youtube player will not play inline on iPhone
> /// setting this to true will force it to play inline
> var alwaysPlayInline : Bool {
>     get {
>         if let playsinline = playerVars["playsinline"] as? String {
>             return playsinline == "1"
>         }
>         return false
>     }
>     set {
>         playerVars["playsinline"] = "\(newValue ? 1 : 0)" as AnyObject?
>       }
> }
> ```

jaywardell
Try to add this code... but nothing... many errors... maybe I not use correctly it. Can you help me please?
on iPad it's ok but on iPhone still goes in fullscreen... wont play inLine... I use WKWebView
Thanks in advance.

**Comment by gilesvangruisen** [comment]
Sorry for the delay here. I'm doing some Spring cleaning, so due to inactivity I'll be closing this issue.

Please leave a comment or open a pull request if this issue persists. Thank you.
