### ISSUE TITLE
Easier access to turning off youtube's default controls

### ISSUE THREAD

**Issue by jaywardell** [gilesvangruisen/Swift-YouTube-Player#101]
There is a setting in playerVars for turning off the default controls that youtube provides.  As it takes some research to find this, I propose a convenience parameter to make it easier to access it:

    /// Determines whether to show controls or not
    var showsControls : Bool {
        get {
            if let showsControls = playerVars["controls"] as? String {
                return showsControls == "2"
            }
            return false
        }
        set {
            playerVars["controls"] = "\(newValue ? 2 : 0)" as AnyObject?
        }
    }

**Comment by gilesvangruisen** [comment]
You're on a roll! Any chance you could submit a PR for this, too? Haha

**Comment by jaywardell** [comment]
Sorry. I just got these. I'll try to tackle that tomorrow. Thanks

-- Jay

**Comment by jaywardell** [comment]
Okay to do all three in one PR?

-- Jay

**Comment by gilesvangruisen** [comment]
@jaywardell no rush! Yeah, one PR is fine, but preferably separate commits. Then I can rebase and we can maintain a nice clean git log :) thanks!

**Comment by gilesvangruisen** [comment]
Sorry for the delay here. I'm doing some Spring cleaning, so due to inactivity I'll be closing this issue.

Please leave a comment or open a pull request if this issue persists. Thank you.
