### ISSUE TITLE
eliminate warnings in xcode 8

### ISSUE THREAD

**Issue by jaywardell** [gilesvangruisen/Swift-YouTube-Player#102]
Xcode 8 presents a warning on several lines when evaluatePlayerCommand() is called:

`Result of call to 'evaluatePlayerCommand' is unused`

For example, on, line 196:

    195 open func mute() {
    196     evaluatePlayerCommand("mute()")
    197 }

While this doesn't affect client code if you are using Carthage or CocoaPods, it's still easy enough to fix.

The fix is to simply assign the result to a dummy variable:

    open func mute() {
        _ = evaluatePlayerCommand("mute()")
    }

**Comment by gilesvangruisen** [comment]
Awesome, thanks @jaywardell. Want to submit a PR?

I'd be happy to review and merge :)

**Comment by DavideCan** [comment]
just adding _@discardableResult_ to _evaluatePlayerCommand_ suppress all the warnings of unused result

`    @discardableResult fileprivate func evaluatePlayerCommand(_ command: String) -> String? {`

**Comment by gilesvangruisen** [comment]
closed via #143
