### ISSUE TITLE
Allow video to continue playing when app enters background

### ISSUE THREAD

**Issue by gbattra** [gilesvangruisen/Swift-YouTube-Player#104]
Currently, when the app enters the background, the video stops playing. There should be a way to override this.

**Comment by BigSauce** [comment]
+1

Is there a way to accomplish this with the current version of this library?

**Comment by gilesvangruisen** [comment]
Sorry for the delay here. I'm doing some Spring cleaning, so due to inactivity I'll be closing this issue.

Please leave a comment on #88 or open a pull request if this issue persists. Thank you.
