### ISSUE TITLE
Video play does not rotate to Landscape

### ISSUE THREAD

**Issue by talezion** [gilesvangruisen/Swift-YouTube-Player#107]
Hi,

Could you kindly advise on how to get the video to play on Landscape once phone rotates, even though app only supports Portrait mode?

There is a behaviour when using `AVPlayerViewController`, when rotating, video is full screen on Landscape, even when it is disabled. 

Thank you

**Comment by talezion** [comment]
I followed these steps and locked the entire app to portrait.. 

http://stackoverflow.com/a/28220616/4697535

**Comment by balazsnemeth** [comment]
Finally I sorted this issue out on this way:

```

// MARK: - Orientation

extension AppDelegate {
    func application(_ application: UIApplication, supportedInterfaceOrientationsFor window: UIWindow?) -> UIInterfaceOrientationMask {
        
        // Let webView video to be rotated
        if window != self.window {
            return window?.rootViewController?.supportedInterfaceOrientations ?? .all;
        }
        
        // All other screens are portrait
        return .portrait;
    }
    
}

```
