### ISSUE TITLE
Full screen state

### ISSUE THREAD

**Issue by szuniverse** [gilesvangruisen/Swift-YouTube-Player#11]
Hi 

Is it possible to detect somehow if the video goes to full screen?

**Comment by gilesvangruisen** [comment]
@szuniverse Hi! Sorry for the delay. Thanks for your question.

I suggest checking out the WebKit full screen APIs. If there's some kind of JavaScript method to end full screen mode, you can call that in your `playerStateChanged(videoPlayer: YouTubePlayerView, playerState: YouTubePlayerState)` body, checking for `playerState == .Ended`.

It seems like you're not alone, as @bobbyali requested something similar in #5. I'd certainly be open to merging a feature like this if you want to build it. 

[This Apple doc on "Controller Media with JavaScript"](https://developer.apple.com/library/safari/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/ControllingMediaWithJavaScript/ControllingMediaWithJavaScript.html) might be helpful for starters!

Let me know how it goes :)

**Comment by szuniverse** [comment]
Okey Thanks! :)
