### ISSUE TITLE
crash on subclassing of YouTubePlayerView

### ISSUE THREAD

**Issue by balazsnemeth** [gilesvangruisen/Swift-YouTube-Player#111]
PR is [here](https://github.com/gilesvangruisen/Swift-YouTube-Player/pull/110) 

When I created a subclass of `YouTubePlayerView`, and the `func loadVideoURL` function, the loading of the index file was crashed because it was looked for the wrong module (self.classForCoder pointed to the Bundle of my actual project instead of the YouTubePlayerView's bundle). This results a crash at least when we installing using Cocoapod.

**Comment by balazsnemeth** [comment]
@gilesvangruisen what do you think?

**Comment by gilesvangruisen** [comment]
Closed via 7ae65e4
