### ISSUE TITLE
How to add loading spinner to the loaded video ?

### ISSUE THREAD

**Issue by Mohammed-Eliass** [gilesvangruisen/Swift-YouTube-Player#112]
How to add loading spinner to the view till the video start to show it's thumbnail ?

**Comment by skdevil** [comment]
Any workarounds for this need ?

**Comment by chnouman** [comment]
yes i have you need to use YouTubePlayerDelegate  and then use 

 func playerReady(_ videoPlayer: YouTubePlayerView){
        
        SVProgressHUD.dismiss()
        
    }

don't forget to add 
videoPlayer.delegate = self.

**Comment by gilesvangruisen** [comment]
Sorry for the delay here. I'm doing some Spring cleaning, so due to inactivity I'll be closing this issue.

Please leave a comment or open a pull request if this issue persists. Thank you.
