### ISSUE TITLE
Unknown class YouTubePlayerView in Interface Builder file.

### ISSUE THREAD

**Issue by yadavanand** [gilesvangruisen/Swift-YouTube-Player#123]
![screen shot 2017-05-26 at 5 54 34 pm](https://cloud.githubusercontent.com/assets/8654980/26494786/0cc89a40-423e-11e7-8252-53cda9e62241.png)
I successfully installed YouTubePlayer using cocoapods to my project, the installation worked perfectly fine and followed the steps in the installation guide to use it , but when try i to play a video i get the following error  "Unknown class YouTubePlayerView in Interface Builder file."  My code

 `import UIKit
 import YouTubePlayer

class PlayerView: UIViewController {

    @IBOutlet var playerView: YouTubePlayerView!

   override func viewDidLoad() {
        super.viewDidLoad() 
    }
   override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(true)
       
        let myVideoURL = URL(string: "https://www.youtube.com/embed/2aaH5lbu398")
        playerView.loadVideoURL(myVideoURL!)
    }`

Please help

**Comment by yadavanand** [comment]
Just add Module YouTubePlayer to storyboard to fix this issue

**Comment by ivanicspeter92** [comment]
I faced the same problem but initially adding the module did not resolve. I had to add the library to the linked frameworks and libraries in the project settings. 
![screen shot 2017-06-21 at 10 00 01](https://user-images.githubusercontent.com/12786524/27371193-6da5cdc2-5668-11e7-9c3e-a0b0761fdff0.png)

**Comment by Aishly** [comment]
because u dint set module class for that view add "YouTubePlayer"
