### ISSUE TITLE
Video not loading/Playing

### ISSUE THREAD

**Issue by yadavanand** [gilesvangruisen/Swift-YouTube-Player#124]
I successfully installed cocoapods and am using the following code but my video does not load 
`import UIKit
import YouTubePlayer

class PlayerView: UIViewController {
    
    
    @IBOutlet var playerView: YouTubePlayerView!
    let myVideoURL = URL(string: "https://www.youtube.com/embed/2aaH5lbu398")
    
  override func viewDidLoad() {
        super.viewDidLoad()
        // begin receiving remote events
        UIApplication.shared.beginReceivingRemoteControlEvents()
        playerView.delegate = self
        playerView.loadVideoURL(myVideoURL!)
        
    }
extension PlayerView:YouTubePlayerDelegate{
    
    func playerReady(_ videoPlayer: YouTubePlayerView){
         print("Player Ready!")
        playerView.play()
    }
    func playerStateChanged(_ videoPlayer: YouTubePlayerView, playerState: YouTubePlayerState){
        print("Player state changed! \(playerState)")
    }
    func playerQualityChanged(_ videoPlayer: YouTubePlayerView, playbackQuality: YouTubePlaybackQuality){
        
    }
}`
Please suggest what am i doing wrong

**Comment by ardee19** [comment]
change your 
`let myVideoURL = URL(string: "https://www.youtube.com/embed/2aaH5lbu398")` 
to
`let myVideoURL = URL(string: "https://www.youtube.com/watch?v=2aaH5lbu398")`

notice your url is an embed url (used for embedding youtube videos). I believe it needs watch url (the one used when watching in youtube.com)

this works on my test. your original code shows white screen. 

Goodluck!

**Comment by vinayakparmar92** [comment]
@ardee19 Thanks for the update. Faced the same issue. Working now :)

**Comment by ardee19** [comment]
@vinayakparmar92 You're welcome! Glad I could help
