### ISSUE TITLE
Support ipv6 network?

### ISSUE THREAD

**Issue by ibankstory** [gilesvangruisen/Swift-YouTube-Player#126]

**Comment by gilesvangruisen** [comment]
Please feel free to reopen if you are able to provide more context or an actionable issue. Sorry for the delay.

**Comment by baohung02** [comment]
@gilesvangruisen Apple reject my app with IPv6 problem (I use your lib to embedded youtube videos) with message: 

> We discovered one or more bugs in your app when reviewed on iPad running iOS 11.4.1 on Wi-Fi connected to an IPv6 network.
Do you have any idea for this case?
