### ISSUE TITLE
prevent fullscreen

### ISSUE THREAD

**Issue by davidseek** [gilesvangruisen/Swift-YouTube-Player#127]
i know this came up before, but the current answers dont help me. 
how do i prevent the player from entering fullscreen?

already set:

```
open func loadVideoID(_ videoID: String) {
        var playerParams = playerParameters()
        
        playerVars["playsinline"] = "1" as AnyObject
        
        playerParams["videoId"] = videoID as AnyObject?
        playerParams["playsinline"] = "1" as AnyObject
        
        loadWebViewWithParameters(playerParams)
    }
```

still enters fullscreen...

**Comment by davidseek** [comment]
archived it by:

```
fileprivate func playerParameters() -> YouTubePlayerParameters {
        
        return [
            "height": "100%",
            "width": "100%",
            "events": playerCallbacks(),
            "playerVars": [
                
                "playsinline": "1",
                "controls": "0",
                "modestbranding": "1",
                "showinfo": "0",
                "loop": "0",
                "rel": "0"
            ]
        ]
    }
```

**Comment by gilesvangruisen** [comment]
This looks good. Possible to open a PR with these changes? Very sorry for the delay !

**Comment by ayman-karram** [comment]
Now **You Can Avoid change in fileprivate func** and use playerVars variable at YouTubePlayerView 

yourYouTubePlayerView. playerVars = playerVars = [
            "playsinline": "1",
            "controls": "1",
            "modestbranding": "1",
            "showinfo": "0",
            "loop": "0",
            "rel": "0"
        ] as [String: AnyObject]
