### ISSUE TITLE
Video not playing

### ISSUE THREAD

**Issue by jgreen84** [gilesvangruisen/Swift-YouTube-Player#131]
In the last couple of hours the video has stopped playing in my app. It was working fine before so I thought maybe I'd broken the code but I loaded up the previous TestFlight version that was fine and that is also not playing.

The PlayerState is changing to "playing" but the video isn't playing. I can scroll through the video and a thumbnail of that frame loads just fine but still not playing. Pushing the pause/play button makes no difference.

Any thoughts?

**Comment by ZiadAli** [comment]
I am having the same issue. Has YouTube said anything about why this might be happening?

**Comment by jgreen84** [comment]
Actually I have just discovered this was because there was low space on my phone and so it was not buffering anything
