### ISSUE TITLE
Play local video

### ISSUE THREAD

**Issue by ibhavin** [gilesvangruisen/Swift-YouTube-Player#132]
Can we play local video from bundle or can we play video from URL like this: http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4 (not youtube URL)

**Comment by encikpulasan** [comment]
maybe can use like this? 
```
let myVideoURL = NSURL(string: "https://www.youtube.com/watch?v=wQg3bXrVLtg")
videoPlayer.loadVideoURL(myVideoURL!)
```

**Comment by ibhavin** [comment]
@encikpulasan  I have already mentioned that **not youtube URL**

**Comment by gilesvangruisen** [comment]
@ibhavin Hi there! Thanks for your interest in this library. Unfortunately, I have no plans to add that functionality, as this is specifically for playing YouTube videos, and playing local videos would require a completely different approach. Sorry about that!
