### ISSUE TITLE
How to handle "done" button's event?

### ISSUE THREAD

**Issue by vatsal1992** [gilesvangruisen/Swift-YouTube-Player#134]
Hi, 
First of all, 
thank you so much for this amazing library.

i'm bit confused about, how to handle "done" button's event while playing video?.
![simulator screen shot 15-sep-2017 5 51 19 pm](https://user-images.githubusercontent.com/12713108/30481973-c35d7e58-9a3e-11e7-967e-26f8cbfe0550.png)

**Comment by IAmTheEye** [comment]
Found a solution and posted it on Stackoverflow: https://stackoverflow.com/a/46330289/627985
