### ISSUE TITLE
iPad Full Screen Mode 

### ISSUE THREAD

**Issue by sadaf-behbahani** [gilesvangruisen/Swift-YouTube-Player#136]
Hi , 

I am not able to get the video to play in full screen on iPad. Here is my playerVars : 

let params: YouTubePlayerView.YouTubePlayerParameters = [
                    "controls": 0 as AnyObject,
                    "color": "white" as AnyObject,
                    "iv_load_policy": 3 as AnyObject,
                    "modestbranding": 0 as AnyObject,
                    "playsinline": 0 as AnyObject,
                    "showinfo": 0 as AnyObject,
                    "rel": 0 as AnyObject,
                    "fs": 1 as AnyObject
                ]
can any one help ?

**Comment by gilesvangruisen** [comment]
Apologies for the delay here @sadaf-behbahani. Closing as this is not an actionable issue. Did you manage to get this to work?

**Comment by johnnelm9r** [comment]
My videos still play in fullscreen on iPhone but it wasn't playing fullscreen on iPad. I had to make a change in YouTubePlayer.swift. If you change allowsInlineMediaPlayback to false in this section:

`fileprivate func buildWebView(_ parameters: [String: AnyObject]) {
        webView = UIWebView()
        webView.allowsInlineMediaPlayback = false
        webView.mediaPlaybackRequiresUserAction = false
        webView.delegate = self
        webView.scrollView.isScrollEnabled = false
    }`

it will now play in fullscreen on iPad. Or at least it is working at the time of writing this. I hope that helps.
