### ISSUE TITLE
Swift 4 support?

### ISSUE THREAD

**Issue by vinodiOS** [gilesvangruisen/Swift-YouTube-Player#138]

**Comment by appsird** [comment]
I recently included the latest rev in my project. It compiles and runs without issue. The included example seems to have a number of Swift4 related issues, though the CocoaPod itself compiles without errors - and works as advertised. 

I do receive a number of warnings, which would be nice to remove with a new release (see attached).

![untitled](https://user-images.githubusercontent.com/8471833/33842438-65dd8b1a-de4f-11e7-875a-1bfe5553f47a.png)

**Comment by appsird** [comment]
Oddly, my Podfile has:

  pod 'YouTubePlayer'

And I perform a:

  pod update

It states it updates to version 0.4.0, but I still receive the older
unchanged YouTubePlayer.swft file. Almost as though it is not in the main
branch...

Regardless, I copied the single file into my project, compile, and no
longer receive the warnings. Thanks!





On Wed, Dec 27, 2017 at 6:39 PM, Giles Van Gruisen <notifications@github.com
