### ISSUE TITLE
Video preloading

### ISSUE THREAD

**Issue by andrey-lisovskiy** [gilesvangruisen/Swift-YouTube-Player#140]
Is there any way to preload video, so when user taps play button it is already loaded and just plays without delay?

**Comment by gilesvangruisen** [comment]
Hi @andrey-lisovskiy! Thanks for opening this issue. There may be a way to do this by loading the player and calling play then pause in rapid succession. Unfortunately, that's a bit janky and out of scope for this library, so I'm going to close this comment. Please let us know back here if you find an approach that works as it could be helpful for others in the future! Thanks!
