### ISSUE TITLE
Nav bar problem, status bar view disappears

### ISSUE THREAD

**Issue by yestay90** [gilesvangruisen/Swift-YouTube-Player#141]
When played on landscape mode and video ends, It goes back to portrait mode. But status bar disappears.

**Comment by gilesvangruisen** [comment]
Hi @yestay90! Sorry for the delay. I don't believe this is the fault of this library, as we do nothing to control or set the properties of the status bar. Closing as it's unrelated and out of scope. Sorry about that!
