### ISSUE TITLE
Accessibility options.

### ISSUE THREAD

**Issue by fishercraigj** [gilesvangruisen/Swift-YouTube-Player#142]
See attached screenshot for reference.

During playback these issues were detected during accessibility testing:

1) The “zoom” button has no accessibility label or hints as to what this button does.  There's also no zoom button when in landscape mode.

2) After selecting the media selection button, the audio & subtitles view appears.  After making a selection, there is no way to clear the view and go back to the video.  The “Audio & Subtitles” view will close once the video has stopped playing so the user just has to wait until then.

![screen shot 2017-12-19 at 11 28 12 am](https://user-images.githubusercontent.com/1421161/34175019-d3a1c93e-e4af-11e7-86b4-2e9c8104b033.png)

**Comment by gilesvangruisen** [comment]
Hey @fishercraigj! Thanks for opening this issue. I'm glad to see folks caring about things like accessibility in mobile apps. Unfortunately, this is out of my control. This library is simply a wrapper around YouTube's iFrame Player API, and so all of this UI is defined by them. I would urge you to reach out to YT with these thoughts. 

Closing this as it's out of scope/control. Thanks!
