### ISSUE TITLE
load playlist from a specific song on a playlist

### ISSUE THREAD

**Issue by ilirvg** [gilesvangruisen/Swift-YouTube-Player#15]
I am thinking on having a playlist of videos which will be shown on a collection view. Is there a way to play/load a playlist starting from a specific video?
I have seen that there is a single playlist ID for all of the songs in a playlist, and each video has a individual ID. But can I somehow combine these ID's to start a playlist from  specific video

Best,
Ilir

**Comment by gilesvangruisen** [comment]
Hi @ilirvg! Thanks for using the library. Sorry for the late response.

It looks like this is possible with the iframe API method, `cuePlaylist`. [See here](https://developers.google.com/youtube/iframe_api_reference) for more information on that. Feel free to write an implementation that adds this to the `YouTubePlayer` API. I'd happily review and merge it 😃
