### ISSUE TITLE
Disable log

### ISSUE THREAD

**Issue by kocoai** [gilesvangruisen/Swift-YouTube-Player#152]
Please add option to disable log.

Thank you :)

ps: thank you for excellent work !

**Comment by gilesvangruisen** [comment]
Hi @kocoai sorry for the delay! I agree this would be a useful feature, and I'd happily merge a pull request which introduces the option to disable logging.

I'm going to close this for now but please feel free to comment again or open a pull request with the appropriate changes. Thanks for understanding.
