### ISSUE TITLE
webView nill in buildWebView

### ISSUE THREAD

**Issue by abritopach** [gilesvangruisen/Swift-YouTube-Player#160]
Hello! when the buildWebView method is invoked  I get the following error:

<img width="842" alt="captura de pantalla 2018-06-15 a las 13 42 36" src="https://user-images.githubusercontent.com/2934069/41466381-520bb7e8-70a2-11e8-94f8-924d8d3d348b.png">

Relevant code:

`
import UIKit
import YouTubePlayer

public class YPViewController: UIViewController, YouTubePlayerDelegate {

    @IBOutlet weak var youtubePlayer: YouTubePlayerView!
    public override func viewDidLoad() {
        super.viewDidLoad()
        
        // Do any additional setup after loading the view, typically from a nib.
        let videoId = "WAAZJm6H9Ms";
        
        //self.youtubePlayer = YouTubePlayerView();
        self.youtubePlayer = YouTubePlayerView(frame: CGRect(x: 0, y: 0, width: 200, height: 200))
        self.youtubePlayer.delegate = self;
        self.youtubePlayer.playerVars = ["playsinline": "1" as AnyObject]
        self.youtubePlayer.loadVideoID(videoId);
        
        // youtubePlayer.load(withVideoId: videoId);
    }

    public override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
}

`

How to fix the error?

Thanks!!

**Comment by AshishMultitv** [comment]
I am also receiving the same issue 
![screen shot 2018-08-02 at 2 59 42 pm](https://user-images.githubusercontent.com/40763839/43575564-bd9b3dca-9664-11e8-80d4-e4e44911b819.png)

**Comment by gilesvangruisen** [comment]
Sorry for the delay here. I'm doing some Spring cleaning, so due to inactivity I'll be closing this issue. Seems like this may have been resolved, but please comment or open another Issue if the problem persists. Thank you.
