### ISSUE TITLE
What if I, as a developer, don't want to use the cocoapods or carthage to get a module and want full source code?

### ISSUE THREAD

**Issue by shyamalschandra** [gilesvangruisen/Swift-YouTube-Player#163]
What are the installation and build instructions in that case without using the cocoapods and carthage package insertion?

**Comment by gilesvangruisen** [comment]
Hi @shyamalschandra sorry for the delay. I'm doing some Spring cleaning, so I'll be closing this issue, but let me know if this continues to be a problem. 

There should be no problem installing this outside of a Carthage/Cocoapods contexts, but let me know if you continue to experience issues.

If you've already managed to get it working, I'd be happy to accept a pull request with clarified installation instructions to help future folks :)
