### ISSUE TITLE
Can't rotate video on android

### ISSUE THREAD

**Issue by dkedar20** [gilesvangruisen/Swift-YouTube-Player#166]
I have added the html5 video in my angular 1.4 app it rotate on full screen on IOS but it can't rotate on android devices

if anyone has solution let me know

**Comment by NSMyself** [comment]
I'm not sure what this has to do with that. This repository is for iOS only.

**Comment by gilesvangruisen** [comment]
Sorry for the delay, @dkedar20. This is a library for embedding YouTube videos on iOS targets, so I'm not sure how you got here from Android. Guessing that was a simple mistake, so I'll be closing this issue. Thanks!
