### ISSUE TITLE
How to prevent going to youtube site?

### ISSUE THREAD

**Issue by anonym24** [gilesvangruisen/Swift-YouTube-Player#179]
When you press on title of a video it goes directly to YouTube site and you can't go back anymore (it should not go there in the first play though)

![screenshot_4](https://user-images.githubusercontent.com/8851301/54030029-06c47300-41b3-11e9-909d-89445d501392.png)        ![screenshot_5](https://user-images.githubusercontent.com/8851301/54030033-088e3680-41b3-11e9-9ff0-861e7015a362.png)

When I press the back button it just closes view controller

**Comment by anonym24** [comment]
if it's not possible to disable it, then how set up our webview to open this link in web-browser app instead of webview which is supposed to display only video and don't go to YouTube pages...

**Comment by anonym24** [comment]
It seems we have add some filter, e.g. allow only the next links:

![screenshot_1](https://user-images.githubusercontent.com/8851301/54032861-73dc0680-41bb-11e9-870b-43155cb835dd.png)

`ytplayer://*`, `about:blank` and `https://www.youtube.com/embed/*`

**Comment by anonym24** [comment]
and send them to Safari or other default browser:

            if let url = request.url {
                UIApplication.shared.openURL(url)
            }

**Comment by anonym24** [comment]
I suggest using:

    open func webView(_ webView: UIWebView, shouldStartLoadWith request: URLRequest, navigationType: UIWebView.NavigationType) -> Bool {
        
        if let url = request.url {
            print("link \(url)")
            if navigationType == .linkClicked || (!url.absoluteString.contains("about:blank") && !url.absoluteString.contains("ytplayer://") && !url.absoluteString.contains("youtube.com/embed")) {
                UIApplication.shared.openURL(url)
                return false
            }
            // Check if ytplayer event and, if so, pass to handleJSEvent
            if url.scheme == "ytplayer" {
                handleJSEvent(url)
            }
        }
        return true
    }

**Comment by mhmmdmz** [comment]
My problem is the opposite. For some reason, the redirection doesn't work and I can't redirect the user to YouTube. Unfortunately, this has resulted in a YouTube policy violation and they're now after my life to allow the user to redirect. Any idea how this can be achieved?
