### ISSUE TITLE
Player volume controls

### ISSUE THREAD

**Issue by davut5** [gilesvangruisen/Swift-YouTube-Player#18]
you said that i will make volume up down function later but i am waiting you for 2 mount :( please show me a way. How can i do that?

**Comment by gilesvangruisen** [comment]
Hi @davut5! Sorry for the delay.

I haven't had a lot of demand for volume adjustment, as iOS users typically prefer to adjust system volume using the hardware buttons on their device.

That said, I'm open to merging a feature like this if someone builds it (methods for mute, unmute, set volume). If you're curious, I suggest checking out YouTube's [IFrame API reference](https://developers.google.com/youtube/iframe_api_reference#mute), particularly the section about controlling playback volume/muting that I linked to.
