### ISSUE TITLE
Submitting to App Store

### ISSUE THREAD

**Issue by alexkitcoff** [gilesvangruisen/Swift-YouTube-Player#184]
Has anyone tried to submit an app to the App Store using this? It uses UIWebView, which has been deprecated in favor of WKWebView. The App Store Review Guidelines state:
> 2.5.6 Apps that browse the web must use the appropriate WebKit framework and WebKit Javascript.

**Comment by weakfl** [comment]
See #173

**Comment by alexkitcoff** [comment]
Thanks for the link. I'm still curious whether people have had success submitting to the App Store using the current version with UIWebView. WebKit doesn't allow JavaScript execution in the background, which kills a lot of the functionality in my app.

**Comment by weakfl** [comment]
Since the UIWebView version crashes on iOS 12 it's not really an option anyway.

**Comment by alexkitcoff** [comment]
I have the current version with UIWebView working perfectly on iOS 12.2. The reason it crashes in its current state is due to lines 88 and 235 and in YouTubePlayer.swift.

`public var baseURL = "about:blank"`
`webView.loadHTMLString(htmlString, baseURL: URL(string: baseURL))`

If you delete line 88 and put the baseURL directly in line 235, it works.

`webView.loadHTMLString(htmlString, baseURL: URL(string: "about:blank"))`

I have no idea why this works, but it does.

**Comment by OlegKasarin** [comment]
> I have no idea why this works, but it does.
I have the same crash in example project, because class wasn't initialized from storyboard so baseURL is nil. 
URL cannot be initialized with nil. :)

**Comment by Jswiizle** [comment]
Any update on this? Considering using this library in my next update.

**Comment by gilesvangruisen** [comment]
Hi @Jswiizle et all, sorry for the delay! The transition to `WKWebView` is complete, and you can now access the new version 0.7.0 via Carthage or Cocoapods. Thanks!
