### ISSUE TITLE
Why do you do webView.removeFromSuperview() in layoutSubviews? It pauses playback!

### ISSUE THREAD

**Issue by anonym24** [gilesvangruisen/Swift-YouTube-Player#185]
https://github.com/gilesvangruisen/Swift-YouTube-Player/blob/d5dd459fe65589200490be675221a2f6d23a656e/YouTubePlayer/YouTubePlayer/YouTubePlayer.swift#L124

Why do you do webView.removeFromSuperview() in layoutSubviews? It stops playback!

`layoutSubviews` is called every time controls are being hidden/visible and web is always removed and added to super view which stops video playback.

I removed all of that and now it works fine but why did you add it in the first place?

    override open func layoutSubviews() {
        super.layoutSubviews()
        
        // Remove web view in case it's within view hierarchy, reset frame, add as subview
        webView.removeFromSuperview()
        webView.frame = bounds
        addSubview(webView)
    }

**Comment by anonym24** [comment]
mb it's related to iOS Native Player (in my case I use it, because it gives you fullscreen and nice controls)

so I've edit `layoutSubviews` and added condition to check if webview was added (there is no point to remove and add it again all the time)

**Comment by dri94** [comment]
@anonym24 can you post your edit?
