### ISSUE TITLE
Custom Slider Decoding failed with error code -1

### ISSUE THREAD

**Issue by MBNisha** [gilesvangruisen/Swift-YouTube-Player#188]
Hi,
i have added custom slider and play pause button when i slide forward and backward for some time but getting below issue using OS 12.3.1
AudioSessionSetActive_Priv is passing a serverPID of 0 to CheckRPCError!
Decoding failed with error code -1

**Comment by gilesvangruisen** [comment]
Hi @MBNisha sorry for the delay. It doesn't seem like this would be an issue with this library in particular as we are doing nothing with Audio or Download sessions outside of the web view's internal URL loading and media playback. It's possible this was an issue with `UIWebView` internals. If that's the case, it should no longer be an issue as we have moved to `WKWebView`.

I'm going to close this for now but please feel free to comment again if you think this continues to be an issue that you feel should be handled by this library. Thanks for understanding.
