### ISSUE TITLE
Cannot change the video quality

### ISSUE THREAD

**Issue by gokhandilek** [gilesvangruisen/Swift-YouTube-Player#19]
Hi there,

I am not able to set the video quality. It is streaming the lowest quality at all times.

I set the default quality as follows:
private(set) public var playbackQuality = YouTubePlaybackQuality.HD720

Still cannot get the quality to be 720p. Any help would be appreciated.

Thank you.

**Comment by seenoevo** [comment]
So the quality hasn't been fixed yet?

**Comment by sergeydi** [comment]
Hi, 
I have the same question: How to change video quality?

**Comment by hardiktgreydesk** [comment]
Can we change the playbackQuality ?
