### ISSUE TITLE
Handle auto rotation of device

### ISSUE THREAD

**Issue by skdevil** [gilesvangruisen/Swift-YouTube-Player#191]
Hi, thanks for making this beautiful library. 

**Issue:**  Initially video is played in portrait mode (inside tableView), but after rotating the device, frames are not getting updated. 

How to solve this issue ?

**Comment by gilesvangruisen** [comment]
Hi @skdevil sorry for the delay. This is likely not an issue with this library, as web views behave just like any other view on rotation, and so it is the responsibility of the app developers to ensure their desired behavior in-app. Closing this for now, thank you for understanding.
