### ISSUE TITLE
Any plan to fix UIWebview to WKWebView and Upgrade it to Swift5 compatible methods

### ISSUE THREAD

**Issue by BLPoonia** [gilesvangruisen/Swift-YouTube-Player#195]
Xcode 11.3 and Swift 5

Pod has error. Unable to use. @gilesvangruisen

**Comment by gilesvangruisen** [comment]
Thanks @BLPoonia can you please provide more information and the corresponding error message? I'm aware of some Cocoapods podspec issues that I'm trying to sort out

**Comment by BLPoonia** [comment]
UIWebViewDelegate method (shouldStartLoadWith:) in YoutubePlayer.swift has been replaced and throws compilation error. 

Thus unable to import and use it. 

A quick fix is needed. Ideally UIWebView should be replaced by WKWebView.

**Comment by gilesvangruisen** [comment]
@BLPoonia That's a bit more than a "quick fix" I'm afraid. For now, please downgrade, or you're more than welcome to submit a pull request and I will happily review. Otherwise, I might not be able to get to this until later in the week.

**Comment by FamousMaxy** [comment]
Apple now not accepting my application because it has UIWebView:

> We identified one or more issues with a recent delivery for your app,********. Your delivery was successful, but you may wish to correct the following issues in your next delivery:
> 
> ITMS-90809: Deprecated API Usage - App updates that use UIWebView will no longer be accepted as of December 2020. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).
> 

Please Fix that as soon possible.

**Comment by BLPoonia** [comment]
@FamousMaxy 
Use this fix until @gilesvangruisen updates the code and pod.

`pod 'YouTubePlayer', :git => 'https://github.com/weakfl/Swift-YouTube-Player.git', :branch => 'use-wkwebview'`

**Comment by YogeshPateliOS** [comment]
Hello I am facing the same issue here please upgrade this to WKWebView. Thank You.

**Comment by gilesvangruisen** [comment]
Hey y’all, really sorry about the delay!

Late last night I pushed the updated, Swift 5 compatible pod. You can now upgrade to 0.6.0 via Cocoapods.

The other issue is the deprecation warning about UIWebView. There are other open issues and PRs which I will take a look at today and try to push an update to support WKWebView.

I’ll close this when that’s updated, but for now, the primary issue of Swift 5 Pod availability should be resolved.

Please let me know if you have any questions. Thank you all for filing the issue and chiming in, and obviously thank you for using this library!

**Comment by umerkiani** [comment]
I had to deploy the build yesterday, but I didn't looked at the issues first and had to face embarrassment in front of client due to this: 

ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability.

Any plans to update to WKWebView?

**Comment by gilesvangruisen** [comment]
@BLPoonia @umerkiani et al: 

the transition to `WKWebview` has been merged and deployed, and v0.7.0 is now also available via Cocoapods.
