### ISSUE TITLE
Disable options

### ISSUE THREAD

**Issue by dkk** [gilesvangruisen/Swift-YouTube-Player#196]
Is it possible to disable the options button (3 vertical dots) or the facebook/twitter sharing options? since they may cause the embedded player to be filled with an unusable login page.

**Comment by gilesvangruisen** [comment]
Hey @dkk thanks for the question. To be honest, I'm not sure. YouTube disabled the "showinfo" player param which turned down some of the overlay info/controls. When I tested, it looks like the share buttons properly open a share sheet on iOS, but that probably does happen on every version of iOS.

**Comment by gilesvangruisen** [comment]
Closing this for now. Please feel free to comment if this continues to be an issue you think should be resolved by this library. Thank you!
