### ISSUE TITLE
Remove actionable items

### ISSUE THREAD

**Issue by Abhishek-NickelFox** [gilesvangruisen/Swift-YouTube-Player#199]
Can we remove user image, watch share and other video recomendations as well???

**Comment by gilesvangruisen** [comment]
Hi @Abhishek-NickelFox there is a limited amount of customization that is possibly, as this library is a fairly simple wrapper around [YouTube's iframe API](https://developers.google.com/youtube/iframe_api_reference). To understand what customization is possible via `playerParams`, please see their documentation.

As I understand it, YouTube does not let you remove most of the items you listed from the player view.
