### ISSUE TITLE
No such module "YouTubePlayer"

### ISSUE THREAD

**Issue by imadeit** [gilesvangruisen/Swift-YouTube-Player#2]
Hi, thanks for providing the swift realization of Youtube player view.
But when I tried to used your library, when I try to call:
import YouTubePlayer
in my ViewController file, the following error is reported:
No such module "YouTubePlayer"
Can you give me some hint?

Thanks very much!

**Comment by gilesvangruisen** [comment]
How are you including the library in your project? I'd suggest using a git submodule.

In your project's root directory:
`$ git submodule add git@github.com:gilesvangruisen/Swift-YouTube-Player.git`

Then drag `YouTubePlayer.xcodeproj` into your project in Xcode. In the "General" tab of your project's target, look for "Embedded Binaries" and click the +. If the library is included as a sub-project, you should see YouTubePlayer listed. Click that and you should be good to go!

**Comment by imadeit** [comment]
@gilesvangruisen 
Thanks very much for your hint.
My project can find the Module now! (^O^)
Right now, I am considering supporting from iOS 7.0, but your library is designed to supporting from iOS 8.0.
So can I just change the deployment target from iOS 8.0 to 7.0 in order that my app can run?
Waiting for your kindly help.
Thanks ahead!

**Comment by gilesvangruisen** [comment]
I'm going to leave it as 8.0+ for now (might change this in the future) but there should be nothing wrong with changing deployment target to 7.0.

Best of luck!

**Comment by davut5** [comment]
gives me....  -bash: $: command not found

**Comment by davut5** [comment]
folder right click and click terminal at folder under list then paste $ git submodule add git@github.com:gilesvangruisen/Swift-YouTube-Player.git  its give me error -bash: $: command not found

**Comment by davut5** [comment]
ohh sorry .. now ok..

**Comment by davut5** [comment]
<myproject.VideoViewController 0x7fc24bc9c770> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key videoplayer.

**Comment by davut5** [comment]
hi man. how can i remove youtube big red button...:(

**Comment by ilirvg** [comment]
@gilesvangruisen 
I have the same problem as imadeit, and I am doing as u have explained here and in the end I am adding in "Embedded Binaries" YouTubePlayer.framework. But YoutubePlayer.framework in "Embedded Binaries" is being red and I am having again the error saying: No such module 'YouTubePlayer'.
Any suggestion would be very helpful  

Cheers

**Comment by gilesvangruisen** [comment]
Updating this thread to reflect that YouTubePlayer now supports Cocoapods and Carthage. Check out the README
