### ISSUE TITLE
Can We Take ScreenShot Of CurrentFrame of Video Using Swift ?

### ISSUE THREAD

**Issue by nitinKareer** [gilesvangruisen/Swift-YouTube-Player#202]

**Comment by gilesvangruisen** [comment]
@nitinKareer thanks for the question! This is outside the scope of this library so I'm going to close this, but if you're interested in taking screenshots, please refer to the `WKWebView` or `CoreGraphics` APIs. 

https://developer.apple.com/documentation/webkit/wkwebview/2873260-takesnapshot
