### ISSUE TITLE
How to set the background colour of the view?

### ISSUE THREAD

**Issue by AlexChesters** [gilesvangruisen/Swift-YouTube-Player#25]
This line (where `videoPlayer` is a `YouTubePlayerView`)

`self.videoPlayer.backgroundColor = UIColor.whiteColor()`

**Comment by AlexChesters** [comment]
D'oh, use the background-color of the css

**Comment by thecritic** [comment]
@AlexChesters Can you elaborate on "use the background-color" of the css ? Did you manage to change the player's background ?

**Comment by seenoevo** [comment]
@thecritic:

I know it's late but I just recently looked at this. If you still haven't figured it out, basically in the YTPlayer.html, add the following

```
<head>
        <style>
            * { margin: 0; padding: 0; }
            html, body { width: 100%; height: 100%; }
        </style>
        **<body style="background-color:red;">**
    </head>
```

**Comment by alfredolucomav** [comment]
Hi @seenoevo ,

Thats not working for me in iOS 13. There's another way?

Best Regards
