### ISSUE TITLE
Audio streaming

### ISSUE THREAD

**Issue by callmeahab** [gilesvangruisen/Swift-YouTube-Player#31]
Just curious is there a way to download only audio from yt?

**Comment by davut5** [comment]
@callmeahab did u find solution about audio download?

**Comment by callmeahab** [comment]
Not really. Got caught up in a lot of work so i didn't have time to work on something either.

**Comment by gilesvangruisen** [comment]
As far as I know, the audio and video tracks for a given YouTube video come from the same file (some video format), so I don't think this is possible. I also can't find anything on the iFrame API about audio-only streaming, so I'm going to close this (for now)
