### ISSUE TITLE
func playerStateChanged is not being called on state change

### ISSUE THREAD

**Issue by logan-pratt** [gilesvangruisen/Swift-YouTube-Player#32]
I added the three delegate functions, but when the player plays, pauses, stops, etc, nothing from my function is happening.

**Comment by logan-pratt** [comment]
Sorry just read through the other issues and found the answer.

**Comment by logan-pratt** [comment]
Turns out they still aren't being called even when I set the delegate of the player to self

**Comment by gilesvangruisen** [comment]
@logan-pratt Hi! Do you mind providing me with some code or the project that you're having trouble with? This seems odd. Those delegates methods should definitely be firing so long as the player's delegate is set to the class that implements those methods.

**Comment by logan-pratt** [comment]
@gilesvangruisen Sure! My viewDidLoad is

        videoPlayer.delegate = self
        videoPlayer.loadVideoID("kIy5aiRdtrc")

and I set up an extension for the delegate

    extension ViewController: YouTubePlayerDelegate {
        func playerStateChanged(videoPlayer: YouTubePlayerView, playerState: YouTubePlayerState) {
            println("changed")
        }
    
        func playerQualityChanged(videoPlayer: YouTubePlayerView, playbackQuality: YouTubePlaybackQuality) {
            println("quality")
        }
        func playerReady(videoPlayer: YouTubePlayerView) {
            println("ready")
        }
    }

**Comment by gilesvangruisen** [comment]
Based on this code, so long as the `viewDidLoad` method is in the same `ViewController`, I don't see why this shouldn't work. Any chance the project is public on GH or could be made public so I can clone and debug?
