### ISSUE TITLE
Can i play video in MediaPlayer. Or Can i save Buffing or video?

### ISSUE THREAD

**Issue by davut5** [gilesvangruisen/Swift-YouTube-Player#36]
is there anyway play youtube video in AVPlayer or AVEngine?

**Comment by owenworley** [comment]
If you want to stay within the iOS app guidelines and you tubes TOS, then not really, no

There is a library called XCDYouTubeKit which will do this, however read this regarding legal implications/rules:

https://github.com/0xced/XCDYouTubeKit/blob/master/README.md

Notably, the 'warning' section in he linked readme file
