### ISSUE TITLE
Restricted playback from VEVO

### ISSUE THREAD

**Issue by jr9098** [gilesvangruisen/Swift-YouTube-Player#38]
it seems like the base URL is not linked to http://www.youtube.com so when I try to view copyrighted content, it gives me this error message, I successfully play copyrighted video on a simple uiWebView and an iFrame, 

 let iframeString = "<iframe width=\"360\" height=\"190\" src=\"http://www.youtube.com/embed/RgKAFK5djSk?playsinline=1&autoplay=1&showinfo=0&modestbranding=1&autohide=1\" frameborder=\"0\"></iframe>"

player.loadHTMLString(iframeString, baseURL: NSURL(string:"http://www.youtube.com"));

setting the baseURL parameter allow me to play any kind of video. is there a quick fix for that in your implementation?

**Comment by Rbabu18** [comment]
Is it possible to show / play vevo videos - When I play VEVO videos, I get a message "..not allowed from certain sites.." with a certain suggestion to play directly in youtube.com to view video 
- is there any way to get around this problem?

**Comment by pcreeves** [comment]
@Rbabu18 did you find a solution?

**Comment by gilesvangruisen** [comment]
Please see #28 for more info on this
