### ISSUE TITLE
Current playback time/duration?

### ISSUE THREAD

**Issue by resnate** [gilesvangruisen/Swift-YouTube-Player#39]
Thanks for making this, only issue I'm currently having is how to get the current playback time/total duration of the video?

**Comment by resnate** [comment]
Currently worked this up:

``` public func getCurrentTime(completion:(youTubeTime: String) -> ()) {
        var youTubeTime:String = ""
        dispatch_async(dispatch_get_main_queue(),{
            if let currentTime = self.webView.stringByEvaluatingJavaScriptFromString("player.getCurrentTime().toString();") {

               completion(youTubeTime: String(Int(Double(currentTime)!)))

            }
        })
        
    }
```

**Comment by gilesvangruisen** [comment]
@resnate Hi! Thanks for using the library. Do you mind submitting a pull request for this? This is something I think would be useful for a lot of other people.

Also, it seems odd to dispatch this to the main thread asynchronously. I think you could simplify this quite a bit and drop the need for a callback/any async stuff:

```Swift
public func getCurrentTime() -> Double? {
    let time = self.webView.stringByEvaluatingJavaScriptFromString("player.getCurrentTime().toString();")
    return time.flatMap(Double.init)
}
```

The same would probably apply for `getDuration`. Does that make sense? Was there a particular reason you were dispatching this to the main thread?

**Comment by resnate** [comment]
Yeah, for some reason I kept getting Web Lock errors without the dispatch_async code, I'm not sure why, still getting to grips with Swift.

**Comment by owenworley** [comment]
I have opened a PR for this here:
https://github.com/gilesvangruisen/Swift-YouTube-Player/pulls
As I have a need for the same feature in the app I am working oat the moment

**Comment by gilesvangruisen** [comment]
#45 fixed this
