### ISSUE TITLE
Why YouTubePlayerView Eating so many Memory?

### ISSUE THREAD

**Issue by burhanaksendir** [gilesvangruisen/Swift-YouTube-Player#4]
Could anyone help me with this? How could I reduce the memory for this?

**Comment by gilesvangruisen** [comment]
I'm unable to reproduce this. Closing for now. Please reopen if you can provide concrete steps to reproduce the issue.

**Comment by driver733** [comment]
I have faced the same issue. With every video open +20mb of memory are used.
Steps to reproduce
youTube player as property
 
      
          self.player = YouTubePlayerView(frame: self.view.frame)
          self.player.delegate = self
          self.player.loadVideoID("wQg3bXrVLtg")



Open a video. Close it. Open up another one (in different VC). Check memory usage.
After youTube view is dismissed memory usage remains the same (does not decrease).

**Comment by driver733** [comment]
Here is an instruments file, if it can help.
https://www.dropbox.com/s/jevnzb584wwq8ij/Instruments.trace.zip?dl=0

**Comment by jr9098** [comment]
playerView.clear() before playing a new video, this solved the problem for me, but Battery usage remains high and very high when loading video
