### ISSUE TITLE
Cocoa Pods/Cathrage Don't Install

### ISSUE THREAD

**Issue by rinyfo4** [gilesvangruisen/Swift-YouTube-Player#40]
[XCODE 7.1 Swift 2]

Hey

I followed the instructions for adding the Carthage file and the I wasn't able to find the frameworks I had to add to the `Link Library With Binary`. 

I tried adding the cocoa-pods and it just keeps "updating": "Updating local specs repositories" and doesn't change. I've been waiting for several minutes... 

My project was set on iOS 9.1. I then set it to 7.0 and nothing changed.

Any ideas if I'm doing something wrong or if this is a bug for Swift 2? 

Thanks guys.

**Comment by rinyfo4** [comment]
I installed in manually an it works. https://github.com/rinyfo4/YoutubePlayer_Swift_SIMPLE-

**Comment by gilesvangruisen** [comment]
@rinyfo4 Hi! In the `Link Library With Binary` step, you'll have to click `Add Other…` and navigate to `Carthage/Build/…` yourself to add the library. Only Apple's library and others included in the project/workspace will show up in that nice list they give you.

Hope this helps, please let me know if that helps or if you think I should clarify the `README`.

Thanks for using the library!!
