### ISSUE TITLE
XCode 7, Pod Import

### ISSUE THREAD

**Issue by Schachte** [gilesvangruisen/Swift-YouTube-Player#42]
PodFile  
1 platform :ios, '8.0'
  2 use_frameworks!
  3 pod 'YouTubePlayer'

Run pod install, pod update.

I create a new XCode project and import YoutubePlayer, but it says the module is not found. What is the cause for this? I'm running XCode 7.

**Comment by Schachte** [comment]
imported original repo to project dir, dragged xcode source into project and linked youtube framework in settings.

**Comment by gilesvangruisen** [comment]
Thanks for the update @schachte! And thanks for using the library :)
