### ISSUE TITLE
Can't play videos on SplitViewController on iPad

### ISSUE THREAD

**Issue by KralMurat** [gilesvangruisen/Swift-YouTube-Player#43]
Hello, 

I'm using your library in one of my project (thanks in advice), it works perfectly on iPhone, but i doesn't work properly on iPad.

I use a collectionview on detailviewcontroller, every cell contains a YouTubePlayer view, and when user click an iten, collectionview's didselect methot trigger the player, and it plays on full screen, but on iPad, when i click the collectionView item, i think it plays on background, i can hear the video's voice, but cant see the video. What should i do to open player on splitviewcontroller with full screen?

Here is my collectionView's didSelect method:

```
    timer = NSTimer.scheduledTimerWithTimeInterval(4, target: self, selector: "alertVideo", userInfo: nil, repeats: false)
    NSNotificationCenter.defaultCenter().addObserver(self, selector: "doneButton",  name: UIWindowDidBecomeHiddenNotification, object:nil)
    NSNotificationCenter.defaultCenter().addObserver(self, selector: "startVideo",  name: UIWindowDidBecomeVisibleNotification , object:nil)
    let a = MBProgressHUD.showHUDAddedTo(self.view, animated: true)
    a.dimBackground = true
    collectionView.deselectItemAtIndexPath(indexPath, animated: true)
    let cell = collectionView.cellForItemAtIndexPath(indexPath)
    let circleView : YouTubePlayerView? = (cell!.contentView.viewWithTag(10)) as? YouTubePlayerView

    circleView?.play()
```

**Comment by KralMurat** [comment]
I forgot to say that detailViewController is belongs to splitViewController.

**Comment by johnnelm9r** [comment]
My videos still play in fullscreen on iPhone but it wasn't playing fullscreen on iPad. I had to make a change in YouTubePlayer.swift. If you change allowsInlineMediaPlayback to false in this section:

`fileprivate func buildWebView(_ parameters: [String: AnyObject]) {
        webView = UIWebView()
        webView.allowsInlineMediaPlayback = false
        webView.mediaPlaybackRequiresUserAction = false
        webView.delegate = self
        webView.scrollView.isScrollEnabled = false
    }`

it will now play in fullscreen on iPad. Or at least it is working at the time of writing this. I hope that helps.
