### ISSUE TITLE
playerState on Done pressed support

### ISSUE THREAD

**Issue by talezion** [gilesvangruisen/Swift-YouTube-Player#47]
Can we have a new state on Done pressed? At the moment both pause and done buttons pressed represent .Pause.

Thank you. Great player..

**Comment by PizzaBrandon** [comment]
👍 I was hoping to find the same functionality. I don't have a workaround yet, but I'd like to be able to take a different action when `Done` is pressed than just pausing the video.

**Comment by Gerst20051** [comment]
👍

**Comment by eugenio35** [comment]
have you guys found a solution for this?

Thanks
