### ISSUE TITLE
Parse YouTube embed links

### ISSUE THREAD

**Issue by talezion** [gilesvangruisen/Swift-YouTube-Player#48]
I am trying to load links with embed in it, i.e https://www.youtube.com/embed/zW0oWoTMahM. It doesnt seem to work, only when I have the ID "zW0oWoTMahM" it works. Can we load an embed link?

Thanks

**Comment by gilesvangruisen** [comment]
Hi @talezion I apologize for the delay. I've determined this is outside of the scope of this library. To accomplish this functionality, you can parse the final segment of that URL string and pass it to `videoPlayer.loadVideoID(...)`.
