### ISSUE TITLE
Close webview after video finishes?

### ISSUE THREAD

**Issue by bobbyali** [gilesvangruisen/Swift-YouTube-Player#5]
Is there a way to close the player webView after the video has ended? At the moment it remains full-screen and I have to manually press the player "Done" button to close it. (I'm working on an application for kids where I need the video player to automatically close after the video stops.) Any suggestions would be appreciated!

**Comment by adolfo** [comment]
@bobbyali have you tried registering as the `YouTubePlayerDelegate` and then in  `playerStateChanged(videoPlayer: YouTubePlayerView, playerState: YouTubePlayerState)` dismissing the player if `YoutTubePlayerState == .Ended`?

**Comment by gilesvangruisen** [comment]
@bobbyali Hi Bobby!

Thanks for the feedback, but I believe this is out of the scope of this library.

You might have some luck checking out the WebKit fullscreen APIs, but I don't know for sure. Sorry about that.
