### ISSUE TITLE
Player still showing controls even after adding playerVars

### ISSUE THREAD

**Issue by matsura** [gilesvangruisen/Swift-YouTube-Player#50]
Hi,

I'm working on a project and using your Swift Youtube player. Currently, when I set the playerVars to these values:

public static let YOUTUBE_PARAMS = [
        "playsinline": "0",
        "controls": "0",
        "showinfo": "0",
        "autoplay" : "1",
        "fs" : "1",
        "modestbranding" : "1"
    ]

The changes are not active when the video plays. I checked in the debugger and they are applied to the playerVars, but not in the control. 

I have also tried hard coding the values into the .html files, only substituting the videoId. Controls are still visible, and user is able to user them. Parameters seem to have no effect. What could I be doing wrong?

EDIT: I have noticed this is not happening on IPad, but only on smaller devices.

IOS 9.2

**Comment by Mohammed-Eliass** [comment]
facing the same problem

**Comment by ankit0812** [comment]
did you resolve this on anyway? @matsura  @Mohammed-Eliass

**Comment by gilesvangruisen** [comment]
Sorry for the delay here. I'm doing some Spring cleaning, so due to inactivity I'll be closing this issue. Please comment or open another Issue if the problem persists. Thank you.
