### ISSUE TITLE
Retain cycle

### ISSUE THREAD

**Issue by lsd2323** [gilesvangruisen/Swift-YouTube-Player#54]
Currently public  var delegate: YouTubePlayerDelegate? is strong reference, that causes to retain cycle. 
Easy to fix, but I was unable to make a pull request, so:
1) add word "class" to:  public protocol YouTubePlayerDelegate : class { ... }
2) public weak var delegate: YouTubePlayerDelegate?

**Comment by DCDJ** [comment]
Thanks so much for this - spent ages trying to figure out why my instance wasn't being deinitialized properly (I assumed strong reference) and was able to narrow it down to the YouTubePlayerDelegate - didn't realise it was a strong reference!

@gilesvangruisen if you could implement this that would be great!

**Comment by lsd2323** [comment]
You are welcome! Thanks to  @gilesvangruisen for this awesome lib!

**Comment by gilesvangruisen** [comment]
I merged a PR that should fix this by making the delegate reference `weak` adding a `class`-requirement to the `YouTubePlayerDelegate` protocol.
