### ISSUE TITLE
Set "Referer" header for blocked YouTube Videos

### ISSUE THREAD

**Issue by DCDJ** [gilesvangruisen/Swift-YouTube-Player#57]
Would it be possible to set the forHTTPHeaderField: "Referer" field to "https://www.youtube.com" in the webView request so we can avoid videos being blocked on iOS?

Thanks, would be much appreciated!!

**Comment by DCDJ** [comment]
Just realised this can be done by setting the baseURL of the webView HTML loader function to YouTube:

`webView.loadHTMLString(htmlString, baseURL: NSURL(string: "http://www.youtube.com"))`

**Comment by DCDJ** [comment]
This approach seems to break the event handling.. still trying to figure this one out

**Comment by DCDJ** [comment]
Nevermind, I'm being an idiot - events do work with this approach!

**Comment by alexkitcoff** [comment]
I'm trying to figure this out as well. I set the baseURL to http://www.youtube.com and still can't bypass video restrictions. Did you ever figure out a solution?
