### ISSUE TITLE
Play next video in playlist?

### ISSUE THREAD

**Issue by seenoevo** [gilesvangruisen/Swift-YouTube-Player#58]
I just started using this library and I have a playlist of videos I'd like to play.

I have:

```
func playerReady(videoPlayer: YouTubePlayerView)
    {
        print("ready")
        if videoPlayer.ready
        {
            videoPlayer.loadPlaylistID("PLxnnlv22Xcq14K9mn7qAg4uTQ4_D-ys9l")
        }
    }
```

which I call and pass in playerReady(self.videoPlayer).

However, I'm still a beginner. The beginning of the video just flashes constantly and doesn't play. I know I'm doing something wrong, but I'm not sure how to set it up.

Can anyone assist?

**Comment by gkye** [comment]
You should load the playlist before checking if the player is ready. Example using an `viewDidLoad`

```swift
       
    override func viewDidLoad() {
        super.viewDidLoad()
        videoPlayer.loadPlaylistID("PLxnnlv22Xcq14K9mn7qAg4uTQ4_D-ys9l")
    }
    
    func playerReady(videoPlayer: YouTubePlayerView)
    {
        if videoPlayer.ready
        {
            print("ready")
            videoPlayer.play();
        }
    }
    //Next video in playlist
    @IBAction func next(sender: UIButton) {
        playerView.nextVideo()
    }
```

**Comment by seenoevo** [comment]
thanks a lot!

I have another question if you know this.....when I tap the forward button, it closes the FullScreen, then a second later it goes to Full Screen and plays the next video in the playlist.

Do you know how I can prevent the Full-Screen from closing, and just keeping it there to load the next video?

Thanks

**Comment by gkye** [comment]
No problem and I'm not too sure how that can be implemented within a full screen iframe. You could always resize the video player to fit the screen and use your own next and previous controls (I think that's what the current YouTube app does).

**Comment by gkye** [comment]
No problem and I'm not too sure how that can be implemented within a full screen iframe. You could always resize the video player to fit the screen and use your own next and previous controls (I think that's what the current YouTube app does).

**Comment by seenoevo** [comment]
How can I use my own controls? There's no properties I can access that allows users to hide the controls. `MPMoviePlayerController` has a `controlStyle` property but I don't see one for YTPlayer.

**Comment by gkye** [comment]
```swift
playerView.playerVars = [
            "playsinline": "1",
            "controls": "0",
            "showinfo": "0"
        ]
```
Take a look at the demo project and also read the api docs for a better understanding of what the parameters do [https://developers.google.com/youtube/player_parameters](docs)

**Comment by gilesvangruisen** [comment]
Sorry for the delay here. I'm doing some Spring cleaning, so due to inactivity I'll be closing this issue. Please comment or open another Issue if the problem persists. Thank you.
