### ISSUE TITLE
All player vars

### ISSUE THREAD

**Issue by SmileAppDev** [gilesvangruisen/Swift-YouTube-Player#59]
Could we get a list of all the possible player vars?

**Comment by gkye** [comment]
https://developers.google.com/youtube/player_parameters

**Comment by jr9098** [comment]
Up, player vars "showinfo" : "0" and "modestbranding" : "1" seems to be self exclusive, both parameters work when alone but when putting them together, modestbranding is ignored, any solution? I don't want to be able to tap a link inside the player.

**Comment by gilesvangruisen** [comment]
I'm going to close this since it doesn't seem to be an issue with the library itself. Thanks!
