### ISSUE TITLE
Turn off fullscreen?

### ISSUE THREAD

**Issue by erikdung** [gilesvangruisen/Swift-YouTube-Player#6]
Hi,
Is it possible to turn off autofullscreen? Thanks

**Comment by gilesvangruisen** [comment]
@erikdung you'll need to ensure your `playerVars` include `["playsinline": "1"]`

Note that YouTube requires it be set to 1, rather than true. 

Hope this helps!

**Comment by erikdung** [comment]
It doesn't work on iPhone....
I set it like this:
public func loadPlaylistID(playlistID: String) {
        // No videoId necessary when listType = playlist, list = [playlist Id]
        playerVars["listType"] = "playlist"
        playerVars["list"] = playlistID
        playerVars["playsinline"] = true

        loadWebViewWithParameters(playerParameters())
    }

**Comment by erikdung** [comment]
My fault, I used loadVideoID func, so I fixed it to: 

public func loadVideoID(videoID: String) {
        playerVars["playsinline"] = "1"
        var playerParams = playerParameters()
        playerParams["videoId"] = videoID
        playerParams["playsinline"] = "1"

        loadWebViewWithParameters(playerParams)
    }

and it works. Thanks

**Comment by davidseek** [comment]
doesnt work for me... took the exact values from "erikdung commented on Mar 29, 2015"
