### ISSUE TITLE
i am not able to play video automatically and also not able to remove suggestion 

### ISSUE THREAD

**Issue by ghimireprashant** [gilesvangruisen/Swift-YouTube-Player#61]
let myVideoURL = NSURL(string:urlString)
        videoPlayer.playerVars = [
            "playsinline": "1",
            "controls": "1",
            "autoplay": "1",
            "showinfo": "1",
            "autohide":"1",
            "modestbranding":"1",
            "rel":1

```
    ]

    videoPlayer.loadVideoURL(myVideoURL!)
    self.youtubeView .addSubview(videoPlayer)
```

here is my code.
i want to remove red button and want to auto play the video.i also want to remove suggestion video and advertisement (if possible).please help me thank you.

**Comment by nghtho94** [comment]
same issue :'(

**Comment by szalaidaniel** [comment]
Not the best solution, but with NSTimer works for me.

**Comment by nghtho94** [comment]
i have been try NSTimer we need a calback function. then i try another API. all of you should use youtube offfical api 'youtube-ios-player-helper'. I use it with swift . perfect

**Comment by szalaidaniel** [comment]
_class PlayerViewController: UIViewController,_ **YouTubePlayerDelegate** {

_viewDidLoad_
**playerViewVariable.delegate = self**

**Comment by commando24** [comment]
for removing suggestion set rel to 0.that will remove suggestion.
videoPlayer.playerVars = ["rel" : "0" ] like this.

**Comment by moquiutijunio** [comment]
I resolved this problem using delegate, with method 

func playerReady(_ videoPlayer: YouTubePlayerView) {
        videoPlayer.play()
    }

**Comment by gilesvangruisen** [comment]
Sorry for the delay here. I'm doing some Spring cleaning, so due to inactivity I'll be closing this issue. Seems like this has been resolved, but please comment or open another Issue if the problem persists. Thank you.
