### ISSUE TITLE
Exceptions thrown

### ISSUE THREAD

**Issue by ogezue** [gilesvangruisen/Swift-YouTube-Player#63]
Are you aware that the symbolic breakpoint "All Exceptions" catches a lot of exception when a video is played? Is this ok or can it be improved?

**Comment by gilesvangruisen** [comment]
Hi @ogezue sorry for the late reply, but thanks for using the library!

Can you elaborate on this a bit? Maybe share some of the exceptions that you're seeing? Thanks!

**Comment by ogezue** [comment]
Hi @gilesvangruisen - I think you should see the error if you enable the symbolic breakpoint for all exceptions an run an app with your library. I think I can give a more detailed answer next week.

**Comment by reinderdevries** [comment]
@ogezue Do you mean the exception below? 

I've seen it a lot, and the app halts like you say when creating an Exception breakpoint for All Exceptions. Tried to solve it, to no avail, it appears to originate from the webview itself. I imagine switching to WKWebView would solve errors like these in the future.

	2016-09-03 15:36:05.751 [850:268880] This application is modifying the autolayout engine from a background thread, which can lead to engine corruption and weird crashes.  This will cause an exception in a future release.
	 Stack:(
		0   CoreFoundation                      0x0000000182712dc8 <redacted> + 148
		1   libobjc.A.dylib                     0x0000000181d77f80 objc_exception_throw + 56
		2   CoreFoundation                      0x0000000182712cf8 <redacted> + 0
		3   Foundation                          0x00000001831c3b2c <redacted> + 88
		4   Foundation                          0x0000000183044c3c <redacted> + 36
		5   UIKit                               0x000000018797cd98 <redacted> + 64
		6   UIKit                               0x000000018797d8b0 <redacted> + 244
		7   UIKit                               0x000000018810b7f0 <redacted> + 268
		8   UIKit                               0x0000000187b88aa0 <redacted> + 176
		9   UIKit                               0x00000001878701e4 <redacted> + 656
		10  QuartzCore                          0x00000001851fe98c <redacted> + 148
		11  QuartzCore                          0x00000001851f95c8 <redacted> + 292
		12  QuartzCore                          0x00000001851f9488 <redacted> + 32
		13  QuartzCore                          0x00000001851f8ab8 <redacted> + 252
		14  QuartzCore                          0x00000001851f8818 <redacted> + 500
		15  WebCore                             0x00000001873d53c0 <redacted> + 176
		16  WebCore                             0x00000001873982c4 <redacted> + 368
		17  CoreFoundation                      0x00000001826c909c <redacted> + 24
		18  CoreFoundation                      0x00000001826c8b30 <redacted> + 540
		19  CoreFoundation                      0x00000001826c6830 <redacted> + 724
		20  CoreFoundation                      0x00000001825f0c50 CFRunLoopRunSpecific + 384
		21  WebCore                             0x00000001865e2108 <redacted> + 456
		22  libsystem_pthread.dylib             0x0000000182377b28 <redacted> + 156
		23  libsystem_pthread.dylib             0x0000000182377a8c <redacted> + 0
		24  libsystem_pthread.dylib             0x0000000182375028 thread_start + 4
	)

**Comment by gilesvangruisen** [comment]
Hi @ogezue and @reinderdevries! Are you still seeing this issue?

We're not really doing any active layout work in this library, so this seems like an odd error. Do you think the `UIWebView` is modifying the layout engine off-main-thread? That would also seem surprising. 

Would love to hear more information on this, or hear if you were able to fix it using `WKWebView`, otherwise I'll assume it was due to something unrelated and close this.

**Comment by reinderdevries** [comment]
It's odd, right? I'm assuming it's the web view that's causing the layout changes off the main thread. Normally a stack trace would show the offending code, but these stacks always show internal calls.

`WKWebView` would probably remove the issue, and it isn't a bad idea to upgrade the library anyway. At this time I'm not actively working on the project that uses Swift-YouTube-Player, but when the error keeps popping up I'll consider rewriting to WKWebView.

**Comment by ogezue** [comment]
Thanks  - I think you can close this issue. It is working fine now.

**Comment by gilesvangruisen** [comment]
Sorry for the delay here. I'm doing some Spring cleaning, so due to inactivity I'll be closing this issue. Seems like this may have been resolved, but please comment or open another Issue if the problem persists. Thank you.
