### ISSUE TITLE
getDuration feature doesn't work

### ISSUE THREAD

**Issue by matthewfbenjamin** [gilesvangruisen/Swift-YouTube-Player#67]
As the title suggests the getDuration feature didn't work in the example project or the project I'm working on now. Has anyone had this problem?

**Comment by Calderis** [comment]
Same here :/

**Comment by gilesvangruisen** [comment]
What seems to happen when you try to call `getDuration`? In my experience, it seems to return the accurate duration.

**Comment by Treverr** [comment]
Mine doesn't even have it as an option, its nowhere to be found in the project so I cannot even call it.

**Comment by jr9098** [comment]
getDuration is not in the file when installing with Cocoapods pod install and my project doesn't build anymore, is there a quick fix?

**Comment by riarellano** [comment]
Try changing your podfile to contain the latest commit, 
pod 'YouTubePlayer', :git => 'https://github.com/gilesvangruisen/Swift-YouTube-Player.git', :commit => '999b971a6b'

**Comment by gilesvangruisen** [comment]
Sorry for the delay here. I'm doing some Spring cleaning, so due to inactivity I'll be closing this issue. Seems like this may have been resolved with an update to the Cocoapods release, but please comment or open another Issue if the problem persists. Thank you.
