### ISSUE TITLE
load another video after current one finish

### ISSUE THREAD

**Issue by jr9098** [gilesvangruisen/Swift-YouTube-Player#68]
Hi, I would like to load another video when playback of the current video is finish, how would I do that?
(I have an array of videoID and I would like to put them in a queue) is that possible?

**Comment by jr9098** [comment]
I came up with a solution, simply change the viewController to extend YoutubePlayerDelegate and add these 2 functions 

func playerReady(playerView: YouTubePlayerView)
    {
        if playerView.ready {
        
            print("ready")
            playerView.play();
        }
    }
    
    func playerStateChanged(playerView: YouTubePlayerView, playerState: YouTubePlayerState) {
        if playerState == YouTubePlayerState.Ended {
            playerView.loadVideoID("IdneKLhsWOQ")
        }
        
    }

this code allows to start the video when the player is ready, and load another video when the video is ended

**Comment by kmcgowan0** [comment]
Hey, could you expand on how you extended the YoutubePlayerDelegate? I'm having trouble getting it to work.
Thanks!

**Comment by szalaidaniel** [comment]
Don't forget **playerView.delegate = self**

**Comment by gilesvangruisen** [comment]
Sorry for the delay here. I'm doing some Spring cleaning, so due to inactivity I'll be closing this issue. Seems like this may have been resolved, but please comment or open another Issue if the problem persists. Thank you.
