### ISSUE TITLE
unable to play with Carthage 

### ISSUE THREAD

**Issue by umeshjavastar** [gilesvangruisen/Swift-YouTube-Player#69]
Hello,
  I am trying to build with Carthage but it doesn't work..
Facing some exception 

> Unknown class YouTubePlayerView in Interface Builder file.

**YouTubePlayerView** file is missing with

> $(SRCROOT)/Carthage/Build/iOS/YouTubePlayer.framework

**Comment by gilesvangruisen** [comment]
Hi @umeshjavastar thanks for using the library! Very sorry for the delay and I hope you sorted out the issue. I have been unable to reproduce this. If you're still hitting this, please ensure you're following the Carthage instructions in the [README](https://github.com/gilesvangruisen/Swift-YouTube-Player/blob/master/README.md)

**Comment by antonioreyna** [comment]
Same problem here. i the package is correctly installed with carthage, i can use it in code but no IB

**Comment by balazsnemeth** [comment]
I got the same error when I not set the proper module in IB. Make sure you set the module beside the class:
![screenshot 2017-03-03 14 09 32](https://cloud.githubusercontent.com/assets/2070044/23552277/49d33efa-001b-11e7-866e-12cd8af9e805.png)
