### ISSUE TITLE
swift 3.0

### ISSUE THREAD

**Issue by WhitneyMFoster** [gilesvangruisen/Swift-YouTube-Player#71]
Could you please make a branch that is swift 3.0 compatible?

**Comment by yoninazarathy** [comment]
+1

**Comment by karthisiva** [comment]
any improvement?????

**Comment by gilesvangruisen** [comment]
Sorry for the delay here. I'm doing some Spring cleaning, so due to inactivity I'll be closing this issue. Thank you.
