### ISSUE TITLE
osx support

### ISSUE THREAD

**Issue by Gerst20051** [gilesvangruisen/Swift-YouTube-Player#72]
any reason why this doesn't support osx?

**Comment by JUSTINMKAUFMAN** [comment]
I am working on this now if you (or anyone is interested in helping). I will post a pull request with my progress.

**Comment by Gerst20051** [comment]
ok i'll take a look

**Comment by gilesvangruisen** [comment]
I'm going to close this in favor of starting a discussion on #74. Thanks @Gerst20051 @JUSTINMKAUFMAN
