### ISSUE TITLE
Warning: no rule to process file YTPlayer.html for architecture arm64

### ISSUE THREAD

**Issue by Gerst20051** [gilesvangruisen/Swift-YouTube-Player#73]
Warning: no rule to process file ```'/Path/To/Pods/YouTubePlayer/YouTubePlayer/YouTubePlayer/YTPlayer.html'``` of type **text.html** for architecture **arm64**

**Comment by Gerst20051** [comment]
I think it is something related to [this](http://xcodar.blogspot.com/2015/01/warning-no-rule-to-process-file-of-type.html).

**Comment by gilesvangruisen** [comment]
Thanks @Gerst20051. I'm closing this since I merged a PR #52 that should fix this and silence the warning. Thanks for using the library! :)
