### ISSUE TITLE
EXC_BAD_INSTRUCTION (code=EXC_i386_INVOP, subcode=0x0) in playerHTMLPath

### ISSUE THREAD

**Issue by kilsoar** [gilesvangruisen/Swift-YouTube-Player#77]
When I want to load a video by calling loadVideoID I get an EXC_BAD_INSTRUCTION (code=EXC_i386_INVOP, subcode=0x0). It stops in the playerHTMLPath and the console prints: "fatal error: unexpectedly found Nil while unwrapping an Optional value"

I use cocoapods and have no Idea why this is not working anymore. Any clues/ideas what's going wrong?

**Comment by gilesvangruisen** [comment]
Hi @kilsoar! I closed this simply because it's a bit old now and since I haven't seen similar reports from anyone else.

Are you still experiencing this issue? Have you set any custom `playerVars`, and if so, what does that object look like?

**Comment by grizzly** [comment]
Same issue here
