### ISSUE TITLE
When i am open project i got error

### ISSUE THREAD

**Issue by patikzetrixweb1234** [gilesvangruisen/Swift-YouTube-Player#78]
no such module 'YouTubePlayer '

**Comment by gilesvangruisen** [comment]
Hi @patikzetrixweb1234 please ensure you are following [the Installation instructions](https://github.com/gilesvangruisen/Swift-YouTube-Player) closely as those have been tested and confirmed to work in a handful of situations. 

Thanks!

**Comment by mitulmarsonia** [comment]
Getting same issue, i'm using pod.
