### ISSUE TITLE
Turn on fullscreen iPad?

### ISSUE THREAD

**Issue by iRoachie** [gilesvangruisen/Swift-YouTube-Player#8]
Can't seem to be able to play full screen for iPad.

 public func loadVideoID(videoID: String) {
        var playerParams = playerParameters()
        playerParams["videoId"] = videoID
        playerParams["playsinline"] = "0"

```
    loadWebViewWithParameters(playerParams)
}
```

The video still plays in line. Any help?

**Comment by tardura** [comment]
Did you find any solution to this? Running into this same problem. I want to display the player inline when the iPad is in landscape or automatically in fullscreen when the iPad is in portrait. I can write the functions required to detect the rotation. However, I have not found a way to force the player into full screen.

**Comment by sadaf-behbahani** [comment]
Having the same issue, Cannot get the player to play in full screen on iPad. Here is my parameters 
 let params: YouTubePlayerView.YouTubePlayerParameters = [
                    "controls": 0 as AnyObject,
                    "color": "white" as AnyObject,
                    "iv_load_policy": 3 as AnyObject,
                    "modestbranding": 0 as AnyObject,
                    "playsinline": 0 as AnyObject,
                    "showinfo": 0 as AnyObject,
                    "rel": 0 as AnyObject,
                    "fs": 1 as AnyObject
                ]

**Comment by rajat-Xprep** [comment]
I am also facing the same issue. Does anyone have the solution for this?

**Comment by johnnelm9r** [comment]
My videos still play in fullscreen on iPhone but it wasn't playing fullscreen on iPad. I had to make a change in YouTubePlayer.swift. If you change allowsInlineMediaPlayback to false in this section:

`fileprivate func buildWebView(_ parameters: [String: AnyObject]) {
        webView = UIWebView()
        webView.allowsInlineMediaPlayback = false
        webView.mediaPlaybackRequiresUserAction = false
        webView.delegate = self
        webView.scrollView.isScrollEnabled = false
    }`

it will now play in fullscreen on iPad. Or at least it is working at the time of writing this. I hope that helps.
