### ISSUE TITLE
Do you want get thumbnail function for this player ?

### ISSUE THREAD

**Issue by lifez** [gilesvangruisen/Swift-YouTube-Player#81]
@gilesvangruisen  Do you want to get thumbnail function for this player ?

I have to modify this library to get a thumbnail for my project. Would you mind if I contribute this function

**Comment by gilesvangruisen** [comment]
Sorry for the delay here. I'm doing some Spring cleaning, so due to inactivity I'll be closing this issue.

Please leave a comment or open a pull request if this is still something you'd like to see added. Thank you.
