### ISSUE TITLE
Play video in background mode

### ISSUE THREAD

**Issue by jr9098** [gilesvangruisen/Swift-YouTube-Player#82]
Is there a way to play a list of videos in the background (Home button pressed, device locked). I'm able to start the video again in control center when I leave my app but when the video is finished, the app crashes and i'm not even capable of debugging, it makes XCode crash :(

any solutions, guides, tutorial on the subject?

**Comment by drewg233** [comment]
Did you figure this out?

**Comment by gilesvangruisen** [comment]
Great question @jr9098 and I apologize for slacking here. There's a bit of discussion on #88 about this, and I'd love to hear from you if you figured something out. cc @drewg233 

Closing this in favor of #88. Thanks!
