### ISSUE TITLE
Picture-In-Picture Support?

### ISSUE THREAD

**Issue by biogerm** [gilesvangruisen/Swift-YouTube-Player#87]
Does anyone has PIP support issue? For me, on my iPad device(Air2 running on iOS 9.3.3), when I enter PIP mode, for example, click the PIP button and then home button, the video floats on the screen but slowly stops playing (volume decreases and eventually stops)

Does anyone get it working? I tried to build my own UIWebView and it was the same problem.

**Comment by biogerm** [comment]
The PIP frame still floats but control buttons seems has no effect.

**Comment by gilesvangruisen** [comment]
Sorry for the delay here. I'm doing some Spring cleaning, so due to inactivity I'll be closing this issue.

Please leave a comment or open a pull request if this is still something you'd like to see added. Thank you.
