### ISSUE TITLE
How to set player parameters ? just like autoplay etc..

### ISSUE THREAD

**Issue by dp4dileep** [gilesvangruisen/Swift-YouTube-Player#92]

**Comment by gilesvangruisen** [comment]
Hi @dp4dileep!

There's a property on `YouTubePlayerView` called `playerVars` which you can set as you wish. See this sample from the example code included in the project:

```swift
playerView.playerVars = [
    "playsinline": "1",
    "controls": "0",
    "showinfo": "0"
]
```
