### ISSUE TITLE
playerView.clear not canceling video loading from queue

### ISSUE THREAD

**Issue by talezion** [gilesvangruisen/Swift-YouTube-Player#94]
I am loading videos on a `collectionView`, and to avoid reusable cells issues, I clear the playerView in `prepareForReuse`. The issue is, if I scroll fast, and the video did not load, it is still in an operation queue, and once it is ready, to shows on the next cell. I tried to hide the playerView for the next cell, but for some reason, the playerView becomes visible once it is ready. Any suggestions, how to load videos on a collection?

Thanks

**Comment by gilesvangruisen** [comment]
Sorry for the delay here. I'm doing some Spring cleaning, so due to inactivity I'll be closing this issue.

Please leave a comment or open a pull request if this issue persists. Thank you.
