### ISSUE TITLE
Upgrade from UIWebView to WKWebView with same functionality?

### ISSUE THREAD

**Issue by stepwellmedia** [gilesvangruisen/Swift-YouTube-Player#96]
I really like the work done here.  I had to change to code a little by hand in order to update for Swift 3.0, but I don't know JavaScript well enough to migrate from UIWebView in UIKit to WKWebView in WebKit.

Any plans to do this per Apple's recommendations?

Thanks.

**Comment by duyanh2912** [comment]
For anyone who might be looking for a WKWebView based version and come across this thread, here is a [fork](https://github.com/duyanh2912/Swift-YouTube-Player) of mine :]

**Comment by gilesvangruisen** [comment]
Sorry for the delay here. I'm doing some Spring cleaning, so due to inactivity I'll be closing this issue.

I've just pushed an update moving to `WKWebView`, but due to some breaking changes I need to make a few updates to the readme before cutting a release. Keep an eye out for that! Thank you.
