### ISSUE TITLE
Vevo Videos "origin" parameter

### ISSUE THREAD

**Issue by ZiadAli** [gilesvangruisen/Swift-YouTube-Player#97]
I am trying to play videos from Vevo and other sources that restrict playback outside of Youtube, but when I add an origin parameter none of the videos play. I updated playerParameters per the following:
fileprivate func playerParameters() -> YouTubePlayerParameters {
        playerVars["playsinline"] = 1 as AnyObject?
        playerVars["controls"] = 0 as AnyObject?
        playerVars["showinfo"] = 0 as AnyObject?
        playerVars["origin"] = ("https://www.example.com") as AnyObject?
        return [
            "modestbranding": 1 as AnyObject,
            "height": "100%" as AnyObject,
            "width": "100%" as AnyObject,
            "events": playerCallbacks() as AnyObject,
            "playerVars": playerVars as AnyObject
        ]
    }

and even though every other parameter works, for some reason when I add the origin parameter nothing plays, and when I take it out I can play videos other than Vevo videos. Any ideas as to why this may be?

**Comment by ZiadAli** [comment]
I figured it out. The origin parameter isn't necessary; where webview.loadhtmlfromstring is called, if you change base url from "about:blank" to "https://www.youtube.com/", you can play Vevo videos.

**Comment by sthielen** [comment]
Thank you @ZiadAli, you're a lifesaver!!

**Comment by ankit0812** [comment]
@ZiadAli You saved my day bro :)

**Comment by gilesvangruisen** [comment]
I apologize again for the delay here. This issue has come up a few times, and I stand firm in my decision not to spoof the user agent video origin, for reasons mentioned here https://github.com/gilesvangruisen/Swift-YouTube-Player/issues/28#issuecomment-122352410:

> VEVO appears to have embed restrictions based on device, so they must be checking the user-agent of the web view. Unfortunately I don't believe there's much way around this without spoofing the user-agent, and I don't particularly want to force everyone who uses this library to break the YouTube/VEVO terms of service by bypassing their content embedding restrictions.

> I'll keep this closed indefinitely. If the iframe player shows messages like this for videos you attempt to play, please know that it is, if anything, due to their (YouTube or the content owner) own restrictions on device/country/video/etc., and nothing specific to this wrapper around the iframe API.

As such, I'm going to close this for now. I do not condone any violation of YouTube's or VEVO's terms of service. Thanks for understanding.
