### ISSUE TITLE
How to hide or disable "Youtube" Logo link

### ISSUE THREAD

**Issue by vigneshPalanisamy87** [gilesvangruisen/Swift-YouTube-Player#98]
![youtube Logo](https://i.stack.imgur.com/BxW9G.png)

I want to hide or disable the link

Thanks

**Comment by vigneshPalanisamy87** [comment]
Hi, if you update the following code like this it help to disable the youtube logo link

```
open func webView(_ webView: UIWebView, shouldStartLoadWith request: URLRequest, navigationType: UIWebViewNavigationType) -> Bool {
        
        let url = request.url
        
        // Check if ytplayer event and, if so, pass to handleJSEvent
        if let url = url, url.scheme == "ytplayer" { handleJSEvent(url) }
        
        if navigationType == UIWebViewNavigationType.LinkClicked {
                UIApplication.sharedApplication().openURL(request.URL)
                return false
        }
        return true
    }

```

Thanks

**Comment by memetcircus** [comment]
@vigneshPalanisamy87 

Shouldn't be? Otherwise it opens the link;

open func webView(_ webView: UIWebView, shouldStartLoadWith request: URLRequest, navigationType: UIWebViewNavigationType) -> Bool {
        
        let url = request.url
        
        // Check if ytplayer event and, if so, pass to handleJSEvent
        if let url = url, url.scheme == "ytplayer" { handleJSEvent(url) }
        
        if navigationType == UIWebViewNavigationType.LinkClicked {
                
                return false
        }
        return true
    }

**Comment by vigneshPalanisamy87** [comment]
@memetcircus 

For disable the link we can delete the openURL line.

If the user, want to view the video in youtube app or browser we need that line.

**Comment by commando24** [comment]
to hide logo set modestbranding to 1 in player parameters.

**Comment by gitIkerKristian** [comment]
This won't disable long press on youtube logo... Any solutions for it?

**Comment by MuhammadNawaz2628** [comment]
set modestbranding = 1

**Comment by mitulmarsonia** [comment]
set modestbranding = 1 not working and i have try above other solution also.

**Comment by gilesvangruisen** [comment]
Sorry for the delay here. I'm doing some Spring cleaning, so due to inactivity I'll be closing this issue.

Please leave a comment or open a pull request if this issue persists. Thank you.
