### ISSUE TITLE
UIWebView inherent memory leak showing up in YouTubePlayer

### ISSUE THREAD

**Issue by stepwellmedia** [gilesvangruisen/Swift-YouTube-Player#99]
The best option would be up somehow upgrade from UIWebView to WKWebView; however, until that happens, there needs to be a mechanisms for handling the memory link issue inherent to UIWebView.  Since the webView variable is private, there is no way to access it to clear it manually.

**Comment by jr9098** [comment]
use playerView.clear() function before loading a video, this will resolve the memory leak

**Comment by commando24** [comment]
@jr9098  still receiving memory warning.

**Comment by omarfraiwan** [comment]
I face the same issue

**Comment by jr9098** [comment]
make sur every instances of the player in your app is cleared before loading another video (see my previous answer), memory usage is still high when loading the video but it goes normal after the video is completely loaded.

**Comment by ismailtosun** [comment]
How can i clear before loading video in tableview ?

**Comment by gilesvangruisen** [comment]
Sorry for the delay here. I'm doing some Spring cleaning, so due to inactivity I'll be closing this issue.

Please leave a comment or open a pull request if this issue persists. Thank you.
